base_path: frontend/messages
pull_request_title: 'Ignore: Testing Crowdin GH Integration'
base_url: 'https://api.crowdin.com'
preserve_hierarchy: false
files:
   - source: /en.json
     translation: /%locale%.json
