version: '3.8'
services:
   strapi:
      build: .
      environment:
         NODE_ENV: production
         STRAPI_VERSION: 4.15.0
         SEED_DB: 'true'
         STRAPI_ADMIN_ENABLE_ADDONS_DANGEROUS_ACTIONS: '${STRAPI_ADMIN_ENABLE_ADDONS_DANGEROUS_ACTIONS}'
         DATABASE_CLIENT: postgres
         DATABASE_NAME: strapi
         DATABASE_HOST: postgres
         DATABASE_PORT: 5432
         DATABASE_USERNAME: strapi
         DATABASE_PASSWORD: strapi
         JWT_SECRET: '${JWT_SECRET}'
         API_TOKEN_SALT: '${API_TOKEN_SALT}'
      ports:
         - '${HOST_PORT:-1337}:1337'
      volumes:
         - ./public:/opt/public
      depends_on:
         - postgres
      command: 'strapi start'

   postgres:
      image: postgres
      environment:
         POSTGRES_DB: strapi
         POSTGRES_USER: strapi
         POSTGRES_PASSWORD: strapi
      volumes:
         - db_data:/var/lib/postgresql/data

volumes:
   db_data:
