name: Build test frontend
description: Builds the test frontend, and caches the next.js cache directory
inputs:
   algolia-api-key:
      description: 'Algolia api key'
      required: true
runs:
   using: 'composite'
   steps:
      - name: Cache Next.js cache directory
        uses: actions/cache@v3
        with:
           path: frontend/.next/cache
           key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
           restore-keys: |
              ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Build Next.js
        env:
           NODE_ENV: test
           NEXT_PUBLIC_STRAPI_ORIGIN: http://localhost:1337
           ALGOLIA_API_KEY: ${{ inputs.ALGOLIA_API_KEY }}
           DEV_API_AUTH_TOKEN: ${{ secrets.DEV_API_AUTH_TOKEN }}
        run: cd frontend && pnpm build
        shell: bash
