name: Build Strapi on Deploy

concurrency:
   group: strapi-deploy
   cancel-in-progress: false

on:
   workflow_dispatch:
   push:
      branches:
         - main
      paths:
         - 'backend/**'

jobs:
   build-strapi:
      runs-on:
         group: react-commerce-production-deploy
      steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Deploy Strapi
           run: backend/strapi-deploy-actions
