name: Playwright

on: [push]
env:
   npm_config_userconfig: './.npmrc'
jobs:
   playwright:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3
         - name: Start strapi server
           run: cd backend && docker-compose up -d
           env:
              JWT_SECRET: 'ci-secret'
              API_TOKEN_SALT: 'Not_A-s3Cr3t-/Qr5iGP0g=='
         - name: Setup and cache pnpm
           uses: ./.github/actions/pnpm-setup
         - name: Install workspaces
           env:
              FONT_AWESOME_NPM_TOKEN: ${{ secrets.FONT_AWESOME_NPM_TOKEN }}
           run: pnpm install

         - run: cd frontend && npx playwright install

         - name: Run Playwright Tests
           env:
              NODE_ENV: test
              NEXT_PUBLIC_STRAPI_ORIGIN: http://localhost:1337
              ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
           run: cd frontend && pnpm playwright:run
