name: Jest tests

on: [push]

jobs:
   jest:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v3

         - uses: actions/setup-node@v3
           with:
              node-version: 18

         - name: Setup and cache pnpm
           uses: ./.github/actions/pnpm-setup
         - name: Install workspaces
           env:
              FONT_AWESOME_NPM_TOKEN: ${{ secrets.FONT_AWESOME_NPM_TOKEN }}
           run: pnpm install:all
         - name: Run Jest tests
           run: pnpm test
           env:
              NEXT_PUBLIC_STRAPI_ORIGIN: http://localhost:1337
              ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
